source 'https://rubygems.org'

gem 'pry'
gem 'rails'
##gem 'sqlite3', '~>1.3.6'
gem 'pg'
#gem 'sass-rails', '~> 5.0'
gem 'sass-rails', '>= 3.2'
gem 'uglifier', '>= 1.3.0'
#gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'rack-flash3'
gem 'bcrypt'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
##gem 'bootstrap-sass', '3.0.2.1'
gem 'bootstrap', '~> 4.3.1'
gem 'sprockets-rails', '~> 2.3.2'
gem 'omniauth'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-google-oauth2'
gem 'figaro'
gem 'dotenv-rails'
gem 'json'
gem 'dalli'
gem 'rails_12factor'
gem 'chart-js-rails'
